import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

import { NavigationBar } from "@/components/navigation-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark flex flex-1 justify-center")}>
        <div className="w-full max-w-[1026px]">
          <NavigationBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
